version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0 # Add Docker orb
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish:
    docker:
      - image: cimg/node:16.10
    environment:
      DOCKER_USERNAME: $DOCKER_USERNAME # Add Docker Hub username as an environment variable
      DOCKER_PASSWORD: $DOCKER_PASSWORD # Add Docker Hub password as an environment variable
    steps:
      - checkout
      - setup_remote_docker: # Set up Docker inside the remote environment
          version: 20.10.7
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t zackfong/education-space:latest .
          docker push zackfong/education-space:latest
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
        requires:
          - test
